#ifndef FBCoreHeaders_h__
#define FBCoreHeaders_h__

#include <FBCore/Base/BitUtil.h>
#include <FBCore/Base/ColourF.h>
#include <FBCore/Base/CoreUtil.h>
#include <FBCore/Base/DataUtil.h>
#include <FBCore/Base/DebugTrace.h>
#include <FBCore/Base/Handle.h>
#include <FBCore/Base/LogManager.h>
#include <FBCore/Base/Node.h>
#include <FBCore/Base/Path.h>
#include <FBCore/Base/PluginMacros.h>
#include <FBCore/Base/Properties.h>
#include <FBCore/Base/VectorUtil.h>
#include <FBCore/Base/SingletonPool.h>
#include <FBCore/Base/XmlUtil.h>

#include <FBCore/Database/DatabaseManager.h>
#include <FBCore/Database/AssetDatabaseManager.h>

#include <FBCore/Interface/IApplicationClient.h>
#include <FBCore/Interface/IApplicationManager.h>

// ai
#include <FBCore/Interface/Ai/IAi.h>
#include <FBCore/Interface/Ai/IAiCompositeGoal.h>
#include <FBCore/Interface/Ai/IAiGoal.h>
#include <FBCore/Interface/Ai/IAiGoalEvaluator.h>
#include <FBCore/Interface/Ai/IAiManager.h>
#include <FBCore/Interface/Ai/IAiSteering3.h>
#include <FBCore/Interface/Ai/IAiTargeting3.h>
#include <FBCore/Interface/Ai/IAiWorld3.h>
#include <FBCore/Interface/Ai/IPathfinder2.h>
#include <FBCore/Interface/Ai/IPathNode2.h>

// aero
#include <FBCore/Interface/Aerodynamics/IAircraft.h>
#include <FBCore/Interface/Aerodynamics/IAircraftControlSurface.h>
#include <FBCore/Interface/Aerodynamics/IAircraftPropWash.h>
#include <FBCore/Interface/Aerodynamics/IAircraftWing.h>
#include <FBCore/Interface/Aerodynamics/IAerodymanicsWind.h>
#include <FBCore/Interface/Aerodynamics/IAircraftCallback.h>
#include <FBCore/Interface/Aerodynamics/IAircraftPowerUnit.h>
#include <FBCore/Interface/Aerodynamics/IAircraftPropeller.h>
#include <FBCore/Interface/Aerodynamics/IAircraftPropellerUnit.h>

// actor
#include <FBCore/Interface/Scene/IActor.h>
#include <FBCore/Interface/Scene/ICameraController.h>
#include <FBCore/Interface/Scene/ICameraManager.h>
#include <FBCore/Interface/Scene/IComponent.h>
#include <FBCore/Interface/Scene/IComponentEvent.h>
#include <FBCore/Interface/Scene/IComponentEventListener.h>
#include <FBCore/Interface/Scene/IDirector.h>
#include <FBCore/Interface/Scene/IEditor.h>
#include <FBCore/Interface/Scene/IPrefab.h>
#include <FBCore/Interface/Scene/IPrefabManager.h>
#include <FBCore/Interface/Scene/IScene.h>
#include <FBCore/Interface/Scene/ISceneManager.h>
#include <FBCore/Interface/Scene/ISubComponent.h>
#include <FBCore/Interface/Scene/ITransform.h>

// animation
#include <FBCore/Interface/Animation/IAnimation.h>
#include <FBCore/Interface/Animation/IAnimationInterface.h>
#include <FBCore/Interface/Animation/IAnimationKeyFrame.h>
#include <FBCore/Interface/Animation/IAnimationMorphKeyFrame.h>
#include <FBCore/Interface/Animation/IAnimationPoseKeyFrame.h>
#include <FBCore/Interface/Animation/IAnimationTimeIndex.h>
#include <FBCore/Interface/Animation/IAnimationTrack.h>
#include <FBCore/Interface/Animation/IAnimationVertexTrack.h>
#include <FBCore/Interface/Animation/IAnimator.h>

// command
#include <FBCore/Interface/System/ICommand.h>
#include <FBCore/Interface/System/ICommandManager.h>
#include <FBCore/Interface/System/ICommandManagerListener.h>
#include <FBCore/Interface/System/IMouseCommand.h>

// core
#include <FBCore/Interface/System/IEvent.h>
#include <FBCore/Interface/System/ILogManager.h>

// database
#include <FBCore/Interface/Database/IDatabase.h>
#include <FBCore/Interface/Database/IDatabaseQuery.h>
#include <FBCore/Interface/Database/IDatabaseManager.h>

// fsm
#include <FBCore/Interface/FSM/IFSM.h>
#include <FBCore/Interface/FSM/IFSMManager.h>
#include <FBCore/Interface/FSM/IFSMListener.h>
#include <FBCore/FSM/FSMListener.h>
#include <FBCore/FSM/FSMManager.h>

// graphics
#include <FBCore/Interface/Graphics/IAnimationController.h>
#include <FBCore/Interface/Graphics/IAnimationStateController.h>
#include <FBCore/Interface/Graphics/IAnimationTextureControl.h>
#include <FBCore/Interface/Graphics/IBillboard.h>
#include <FBCore/Interface/Graphics/IBillboardSet.h>
#include <FBCore/Interface/Graphics/ICamera.h>
#include <FBCore/Interface/Graphics/ICubemap.h>
#include <FBCore/Interface/Graphics/IDebug.h>
#include <FBCore/Interface/Graphics/IDebugLine.h>
#include <FBCore/Interface/Graphics/IDecalCursor.h>
#include <FBCore/Interface/Graphics/IDynamicLines.h>
#include <FBCore/Interface/Graphics/IDynamicMesh.h>
#include <FBCore/Interface/Graphics/IFont.h>
#include <FBCore/Interface/Graphics/IFontManager.h>
#include <FBCore/Interface/Graphics/IFrustum.h>
#include <FBCore/Interface/Graphics/IGraphicsSystem.h>
#include <FBCore/Interface/Graphics/IGraphicsObject.h>
#include <FBCore/Interface/Graphics/IGraphicsMesh.h>
#include <FBCore/Interface/Graphics/IGraphicsSettings.h>
#include <FBCore/Interface/Graphics/ILight.h>
#include <FBCore/Interface/Graphics/IMaterialManager.h>
#include <FBCore/Interface/Graphics/IMaterial.h>
#include <FBCore/Interface/Graphics/IMaterialTexture.h>
#include <FBCore/Interface/Graphics/IMaterialNodeAnimatedTexture.h>
#include <FBCore/Interface/Graphics/IMaterialPass.h>
#include <FBCore/Interface/Graphics/IMaterialTechnique.h>
#include <FBCore/Interface/Graphics/IMaterialTexture.h>
#include <FBCore/Interface/Graphics/IMeshConverter.h>
#include <FBCore/Interface/Graphics/IOverlay.h>
#include <FBCore/Interface/Graphics/IOverlayElementContainer.h>
#include <FBCore/Interface/Graphics/IOverlayElementText.h>
#include <FBCore/Interface/Graphics/IOverlayElementVector.h>
#include <FBCore/Interface/Graphics/IOverlayManager.h>
#include <FBCore/Interface/Graphics/IInstancedObject.h>
#include <FBCore/Interface/Graphics/IInstanceManager.h>
#include <FBCore/Interface/Graphics/IDeferredShadingSystem.h>
#include <FBCore/Interface/Graphics/IMaterialShader.h>
#include <FBCore/Interface/Graphics/IGraphicsScene.h>
#include <FBCore/Interface/Graphics/ISceneNode.h>
#include <FBCore/Interface/Graphics/IScreenSpaceEffect.h>
#include <FBCore/Interface/Graphics/IScreenSpaceEffectRenderer.h>
#include <FBCore/Interface/Graphics/ISprite.h>
#include <FBCore/Interface/Graphics/ISpriteRenderer.h>
#include <FBCore/Interface/Graphics/ITerrain.h>
#include <FBCore/Interface/Graphics/ITerrainBlendMap.h>
#include <FBCore/Interface/Graphics/ITextureManager.h>
#include <FBCore/Interface/Graphics/ITexture.h>
#include <FBCore/Interface/Graphics/ITerrainRayResult.h>
#include <FBCore/Interface/Graphics/IViewport.h>
#include <FBCore/Interface/Graphics/IWater.h>
#include <FBCore/Interface/Graphics/IWindow.h>
#include <FBCore/Interface/Graphics/IWindowEvent.h>
#include <FBCore/Interface/Graphics/IWindowListener.h>

// resource
#include <FBCore/Interface/Resource/IResource.h>
#include <FBCore/Interface/Resource/IResourceManager.h>
#include <FBCore/Interface/Resource/IResourceGroupManager.h>

// particle
#include <FBCore/Interface/Particle/IParticle.h>
#include <FBCore/Interface/Particle/IParticleAffector.h>
#include <FBCore/Interface/Particle/IParticleEmitter.h>
#include <FBCore/Interface/Particle/IParticleManager.h>
#include <FBCore/Interface/Particle/IParticleRenderer.h>
#include <FBCore/Interface/Particle/IParticleSystem.h>
#include <FBCore/Interface/Particle/IParticleSystemBuilder.h>
#include <FBCore/Interface/Particle/IParticleSystemListener.h>
#include <FBCore/Interface/Particle/IParticleTechnique.h>

// ui
#include <FBCore/Interface/UI/IUIAbout.h>
#include <FBCore/Interface/UI/IUIApplication.h>
#include <FBCore/Interface/UI/IUIAnimatedMaterial.h>
#include <FBCore/Interface/UI/IUIAnimatorPosition.h>
#include <FBCore/Interface/UI/IUIAnimatorScale.h>
#include <FBCore/Interface/UI/IUIBar.h>
#include <FBCore/Interface/UI/IUIButton.h>
#include <FBCore/Interface/UI/IUICharacterSelect.h>
#include <FBCore/Interface/UI/IUICheckbox.h>
#include <FBCore/Interface/UI/IUICollapsingHeader.h>
#include <FBCore/Interface/UI/IUIColourPicker.h>
#include <FBCore/Interface/UI/IUIContainer.h>
#include <FBCore/Interface/UI/IUICursor.h>
#include <FBCore/Interface/UI/IUIDialogBox.h>
#include <FBCore/Interface/UI/IUIDropdown.h>
#include <FBCore/Interface/UI/IUIDragSource.h>
#include <FBCore/Interface/UI/IUIDropTarget.h>
#include <FBCore/Interface/UI/IUIElement.h>
#include <FBCore/Interface/UI/IUIEventWindow.h>
#include <FBCore/Interface/UI/IUIFileBrowser.h>
#include <FBCore/Interface/UI/IUIImage.h>
#include <FBCore/Interface/UI/IUIImageArray.h>
#include <FBCore/Interface/UI/IUIInputManager.h>
#include <FBCore/Interface/UI/IUILabelCheckboxPair.h>
#include <FBCore/Interface/UI/IUILabelDropdownPair.h>
#include <FBCore/Interface/UI/IUILabelSliderPair.h>
#include <FBCore/Interface/UI/IUILabelTextInputPair.h>
#include <FBCore/Interface/UI/IUILayout.h>
#include <FBCore/Interface/UI/IUIManager.h>
#include <FBCore/Interface/UI/IUIMenu.h>
#include <FBCore/Interface/UI/IUIMenubar.h>
#include <FBCore/Interface/UI/IUIMenuItem.h>
#include <FBCore/Interface/UI/IUIProfileWindow.h>
#include <FBCore/Interface/UI/IUIProfilerWindow.h>
#include <FBCore/Interface/UI/IUIPropertyGrid.h>
#include <FBCore/Interface/UI/IUIRenderWindow.h>
#include <FBCore/Interface/UI/IUIScrollingText.h>
#include <FBCore/Interface/UI/IUISpinner.h>
#include <FBCore/Interface/UI/IUITabBar.h>
#include <FBCore/Interface/UI/IUITabItem.h>
#include <FBCore/Interface/UI/IUIText.h>
#include <FBCore/Interface/UI/IUITextEntry.h>
#include <FBCore/Interface/UI/IUITerrainEditor.h>
#include <FBCore/Interface/UI/IUIToolbar.h>
#include <FBCore/Interface/UI/IUIToggleButton.h>
#include <FBCore/Interface/UI/IUIToggleGroup.h>
#include <FBCore/Interface/UI/IUITreeCtrl.h>
#include <FBCore/Interface/UI/IUITreeNode.h>
#include <FBCore/Interface/UI/IUIToolbar.h>
#include <FBCore/Interface/UI/IUIVector2.h>
#include <FBCore/Interface/UI/IUIVector3.h>
#include <FBCore/Interface/UI/IUIVector4.h>
#include <FBCore/Interface/UI/IUIWindow.h>

// input
#include <FBCore/Interface/Input/IChordDetector.h>
#include <FBCore/Interface/Input/IGameInput.h>
#include <FBCore/Interface/Input/IGameInputMap.h>
#include <FBCore/Interface/Input/IGameInputState.h>
#include <FBCore/Interface/Input/IInputActionData.h>
#include <FBCore/Interface/Input/IInputConverter.h>
#include <FBCore/Interface/Input/IInputEvent.h>
#include <FBCore/Interface/Input/IInput.h>
#include <FBCore/Interface/Input/IInputDeviceManager.h>
#include <FBCore/Interface/Input/IJoystickState.h>
#include <FBCore/Interface/Input/IKeyboardState.h>
#include <FBCore/Interface/Input/IMouseState.h>
#include <FBCore/Interface/Input/ISequenceDetector.h>
#include <FBCore/Interface/Input/ITapDetector.h>

// io
#include <FBCore/Interface/IO/IFileListener.h>
#include <FBCore/Interface/IO/IFileSystem.h>
#include <FBCore/Interface/IO/IFileList.h>
#include <FBCore/Interface/IO/IStream.h>
#include <FBCore/Interface/IO/IFolderExplorer.h>
#include <FBCore/Interface/IO/IFolderExplorerW.h>
#include <FBCore/Interface/IO/INativeFileDialog.h>

// mesh
#include <FBCore/Interface/Mesh/IIndexBuffer.h>
#include <FBCore/Interface/Mesh/IMesh.h>
#include <FBCore/Interface/Mesh/IMeshLoader.h>
#include <FBCore/Interface/Mesh/IMeshResource.h>
#include <FBCore/Interface/Mesh/ISubMesh.h>
#include <FBCore/Interface/Mesh/IVertexBuffer.h>
#include <FBCore/Interface/Mesh/IVertexDeclaration.h>
#include <FBCore/Interface/Mesh/IVertexElement.h>

// net
#include <FBCore/Interface/Net/INetworkManager.h>
#include <FBCore/Interface/Net/INetworkListener.h>
#include <FBCore/Interface/Net/INetworkStream.h>
#include <FBCore/Interface/Net/INetworkView.h>
#include <FBCore/Interface/Net/IPacket.h>
#include <FBCore/Interface/Net/ISystemAddress.h>

// physics
#include <FBCore/Interface/Physics/FBPhysicsTypes.h>
#include <FBCore/Interface/Physics/ICharacterController2.h>
#include <FBCore/Interface/Physics/ICharacterController3.h>
#include <FBCore/Interface/Physics/IPhysicsMaterial2.h>
#include <FBCore/Interface/Physics/IRigidBody2.h>
#include <FBCore/Interface/Physics/IPhysicsSoftBody2.h>
#include <FBCore/Interface/Physics/IPhysicsShape2.h>
#include <FBCore/Interface/Physics/IPhysicsManager2D.h>
#include <FBCore/Interface/Physics/IPhysicsMaterial3.h>
#include <FBCore/Interface/Physics/IPhysicsParticle2.h>
#include <FBCore/Interface/Physics/IPhysicsParticle3.h>
#include <FBCore/Interface/Physics/IRigidBody3.h>
#include <FBCore/Interface/Physics/IRigidDynamic3.h>
#include <FBCore/Interface/Physics/IPhysicsSoftBody3.h>
#include <FBCore/Interface/Physics/IPhysicsShape3.h>
#include <FBCore/Interface/Physics/IBoxShape2.h>
#include <FBCore/Interface/Physics/IBoxShape3.h>
#include <FBCore/Interface/Physics/ISphereShape2.h>
#include <FBCore/Interface/Physics/ISphereShape3.h>
#include <FBCore/Interface/Physics/IPhysicsManager.h>
#include <FBCore/Interface/Physics/IPhysicsVehicle3.h>
#include <FBCore/Interface/Physics/IPhysicsVehicleInput3.h>
#include <FBCore/Interface/Physics/IPhysicsVehicleWheel3.h>
#include <FBCore/Interface/Physics/ITerrainShape.h>
#include <FBCore/Interface/Physics/IRigidStatic3.h>
#include <FBCore/Interface/Physics/IPhysicsScene2.h>
#include <FBCore/Interface/Physics/IPhysicsScene3.h>
#include <FBCore/Interface/Physics/IConstraintD6.h>
#include <FBCore/Interface/Physics/IConstraintFixed3.h>
#include <FBCore/Interface/Physics/IPlaneShape3.h>
#include <FBCore/Interface/Physics/IConstraintDrive.h>
#include <FBCore/Interface/Physics/IConstraintLinearLimit.h>
#include <FBCore/Interface/Physics/IRigidBody3.h>
#include <FBCore/Interface/Physics/IPhysicsSoftBody3.h>
#include <FBCore/Interface/Physics/IPhysicsShape3.h>
#include <FBCore/Interface/Physics/IPhysicsVehicle3.h>
#include <FBCore/Interface/Physics/IRaycastHit.h>
#include <FBCore/Interface/Physics/IMeshShape.h>

// procedural
#include <FBCore/Interface/Procedural/IProceduralCollision.h>
#include <FBCore/Interface/Procedural/IProceduralManager.h>
#include <FBCore/Interface/Procedural/IBlockGenerator.h>
#include <FBCore/Interface/Procedural/ICityGenerator.h>
#include <FBCore/Interface/Procedural/ICityMap.h>
#include <FBCore/Interface/Procedural/ICityMapData.h>
#include <FBCore/Interface/Procedural/ILot.h>
#include <FBCore/Interface/Procedural/IMeshGenerator.h>
#include <FBCore/Interface/Procedural/IProceduralEngine.h>
#include <FBCore/Interface/Procedural/IProceduralTerrain.h>
#include <FBCore/Interface/Procedural/IProceduralWorld.h>
#include <FBCore/Interface/Procedural/IProceduralScene.h>
#include <FBCore/Interface/Procedural/IProceduralCity.h>
#include <FBCore/Interface/Procedural/IProceduralCityCenter.h>
#include <FBCore/Interface/Procedural/IRoadGenerator.h>
#include <FBCore/Interface/Procedural/IRoad.h>
#include <FBCore/Interface/Procedural/IRoadNode.h>
#include <FBCore/Interface/Procedural/IRoadNetwork.h>
#include <FBCore/Interface/Procedural/IRoadSection.h>
#include <FBCore/Interface/Procedural/IRoadElement.h>
#include <FBCore/Interface/Procedural/ISidewalk.h>
#include <FBCore/Interface/Procedural/ITerrainGenerator.h>
#include <FBCore/Interface/Procedural/IProceduralInput.h>
#include <FBCore/Interface/Procedural/IProceduralOutput.h>

// resource
#include <FBCore/Interface/Resource/IResource.h>
#include <FBCore/Interface/Resource/IResourceListener.h>
#include <FBCore/Interface/Resource/IResourceDatabase.h>
#include <FBCore/Interface/Resource/IMeshManager.h>

// script
#include <FBCore/Interface/Script/IScript.h>
#include <FBCore/Interface/Script/IScriptBind.h>
#include <FBCore/Interface/Script/IScriptBreakpoint.h>
#include <FBCore/Interface/Script/IScriptClass.h>
#include <FBCore/Interface/Script/IScriptData.h>
#include <FBCore/Interface/Script/IScriptEvent.h>
#include <FBCore/Interface/Script/IScriptFunction.h>
#include <FBCore/Interface/Script/IScriptInvoker.h>
#include <FBCore/Interface/Script/IScriptManager.h>
#include <FBCore/Interface/Script/IScriptReceiver.h>
#include <FBCore/Interface/Script/IScriptObject.h>
#include <FBCore/Interface/Script/IScriptVariable.h>

// sound
#include <FBCore/Interface/Sound/ISound2.h>
#include <FBCore/Interface/Sound/ISound3.h>
#include <FBCore/Interface/Sound/ISoundEvent.h>
#include <FBCore/Interface/Sound/ISoundEventGroup.h>
#include <FBCore/Interface/Sound/ISoundEventParam.h>
#include <FBCore/Interface/Sound/ISoundListener3.h>
#include <FBCore/Interface/Sound/ISoundManager.h>
#include <FBCore/Interface/Sound/ISoundPlayer.h>
#include <FBCore/Interface/Sound/ISoundProject.h>

// system
#include <FBCore/Interface/System/IAsyncOperation.h>
#include <FBCore/Interface/System/IEvent.h>
#include <FBCore/Interface/System/IEventListener.h>
#include <FBCore/Interface/System/IProject.h>
#include <FBCore/Interface/System/IConsole.h>
#include <FBCore/Interface/System/IJob.h>
#include <FBCore/Interface/System/IJobGroup.h>
#include <FBCore/Interface/System/IJobQueue.h>
#include <FBCore/Interface/System/IJobListener.h>
#include <FBCore/Interface/System/IOutputManager.h>
#include <FBCore/Interface/System/ITask.h>
#include <FBCore/Interface/System/ITaskManager.h>
#include <FBCore/Interface/System/IThreadPool.h>
#include <FBCore/Interface/System/ITimer.h>
#include <FBCore/Interface/System/IState.h>
#include <FBCore/Interface/System/IStateContext.h>
#include <FBCore/Interface/System/IStateQuery.h>
#include <FBCore/Interface/System/IStateManager.h>
#include <FBCore/Interface/System/IStateListener.h>
#include <FBCore/Interface/System/IStateMessage.h>
#include <FBCore/Interface/System/ITransformNode.h>
#include <FBCore/Interface/System/IProfiler.h>
#include <FBCore/Interface/System/IProfile.h>
#include <FBCore/Interface/System/IFrameGrabber.h>
#include <FBCore/Interface/System/IScheduler.h>
#include <FBCore/Interface/System/IFrameStatistics.h>
#include <FBCore/Interface/System/IWorkerThread.h>
#include <FBCore/Interface/System/ISelectionManager.h>
#include <FBCore/Interface/System/ISystemManager.h>
#include <FBCore/Interface/System/ITransformNode.h>
#include <FBCore/Interface/System/ITransformManager.h>
#include <FBCore/Interface/System/ITransformRoot.h>

// video
#include <FBCore/Interface/Video/IVideo.h>
#include <FBCore/Interface/Video/IVideoManager.h>
#include <FBCore/Interface/Video/IVideoMaterial.h>
#include <FBCore/Interface/Video/IVideoStream.h>
#include <FBCore/Interface/Video/IVideoTexture.h>

// vehicle
#include <FBCore/Interface/Vehicle/IVehicleController.h>
#include <FBCore/Interface/Vehicle/IVehicleComponent.h>
#include <FBCore/Interface/Vehicle/IVehicleManager.h>
#include <FBCore/Interface/Vehicle/ICarController.h>
#include <FBCore/Interface/Vehicle/IDifferential.h>
#include <FBCore/Interface/Vehicle/IVehiclePowerUnit.h>
#include <FBCore/Interface/Vehicle/IGearBox.h>
#include <FBCore/Interface/Vehicle/IWheelController.h>
#include <FBCore/Interface/Vehicle/IBatteryPack.h>
#include <FBCore/Interface/Vehicle/IESController.h>
#include <FBCore/Interface/Vehicle/IVehicleBody.h>
#include <FBCore/Interface/Vehicle/ITruckController.h>

// plugin
#include <FBCore/Interface/System/IPluginEvent.h>
#include <FBCore/Interface/System/IPluginInterface.h>

// math
#include <FBCore/Math/Core/MathUtil.h>
#include <FBCore/Math/Spline/LinearSpline1.h>
#include <FBCore/Math/Spline/LinearSpline2.h>
#include <FBCore/Math/Spline/LinearSpline3.h>
#include <FBCore/Math/Spline/LinearSpline4.h>
#include <FBCore/Math/Spline/RotationalSpline3.h>
#include <FBCore/Math/Euler.h>
#include <FBCore/Math/Polygon2.h>
#include <FBCore/Math/Polygon3.h>
#include <FBCore/Math/Vector2.h>
#include <FBCore/Math/Vector3.h>
#include <FBCore/Math/Vector4.h>

#include <FBCore/Memory/Data.h>
#include <FBCore/Memory/FactoryRegistration.h>
#include <FBCore/Memory/FactoryTemplate.h>
#include <FBCore/Memory/FactoryUtil.h>

#include <FBCore/Resource/CMeshManager.h>
#include <FBCore/Resource/CPrefabManager.h>
#include <FBCore/Resource/CResourceDatabase.h>

#include <FBCore/Rtti/RttiClassDefinition.h>

#include <FBCore/Scene/Components/Component.h>
#include <FBCore/Scene/Components/Camera.h>
#include <FBCore/Scene/Components/ComponentT.h>
#include <FBCore/Scene/Components/Constraint.h>
#include <FBCore/Scene/Components/Collision.h>
#include <FBCore/Scene/Components/CollisionBox.h>
#include <FBCore/Scene/Components/CollisionMesh.h>
#include <FBCore/Scene/Components/CollisionPlane.h>
#include <FBCore/Scene/Components/CollisionSphere.h>
#include <FBCore/Scene/Components/CollisionTerrain.h>
#include <FBCore/Scene/Components/Light.h>
#include <FBCore/Scene/Components/Material.h>
#include <FBCore/Scene/Components/Mesh.h>
#include <FBCore/Scene/Components/MeshRenderer.h>
#include <FBCore/Scene/Components/Rigidbody.h>
#include <FBCore/Scene/Components/Skybox.h>
#include <FBCore/Scene/Components/Transform.h>
#include <FBCore/Scene/Components/Terrain/TerrainSystem.h>
#include <FBCore/Scene/Components/Terrain/TerrainLayer.h>
#include <FBCore/Scene/Components/Terrain/TerrainBlendMap.h>
#include <FBCore/Scene/Components/UserComponent.h>

#include <FBCore/Scene/Components/UI/Button.h>
#include <FBCore/Scene/Components/UI/Layout.h>
#include <FBCore/Scene/Components/UI/Image.h>
#include <FBCore/Scene/Components/UI/InputField.h>
#include <FBCore/Scene/Components/UI/Text.h>
#include <FBCore/Scene/Components/UI/Layout.h>
#include <FBCore/Scene/Components/UI/CanvasTransform.h>

#include <FBCore/Scene/CActor.h>
#include <FBCore/Scene/CameraManager.h>
#include <FBCore/Scene/CSceneManager.h>
#include <FBCore/Scene/CScene.h>

#include <FBCore/Script/ScriptEvent.h>
#include <FBCore/Script/ScriptClass.h>
#include <FBCore/Script/ScriptFunction.h>
#include <FBCore/Script/ScriptInvoker.h>
#include <FBCore/Script/ScriptReceiverAdapter.h>
#include <FBCore/Script/ScriptVariable.h>

#include <FBCore/State/Messages/CommonStateChangeMsgs.h>
#include <FBCore/State/Messages/StateMessageBuffer.h>
#include <FBCore/State/Messages/StateMessageBlendMapValue.h>
#include <FBCore/State/Messages/StateMessageContact2.h>
#include <FBCore/State/Messages/StateFrameData.h>
#include <FBCore/State/Messages/StateMessageDefault.h>
#include <FBCore/State/Messages/StateMessageDirty.h>
#include <FBCore/State/Messages/StateMessageJobStatus.h>
#include <FBCore/State/Messages/StatePhysicsPosition2.h>
#include <FBCore/State/Messages/StatePhysicsVelocity2.h>
#include <FBCore/State/Messages/StatePhysicsDynamicState2.h>
#include <FBCore/State/Messages/StatePhysicsForce2.h>
#include <FBCore/State/Messages/StateMessageFloatValue.h>
#include <FBCore/State/Messages/StateMessageIntValue.h>
#include <FBCore/State/Messages/StateMessageStringValue.h>
#include <FBCore/State/Messages/StateMessageLoad.h>
#include <FBCore/State/Messages/StateMessageSetTexture.h>
#include <FBCore/State/Messages/StateMessageFragmentParam.h>
#include <FBCore/State/Messages/StateMessageVisible.h>
#include <FBCore/State/Messages/StateMessageMaterial.h>
#include <FBCore/State/Messages/StateMessageMaterialName.h>
#include <FBCore/State/Messages/StateMessageOrientation.h>
#include <FBCore/State/Messages/StateMessageParamVector4.h>
#include <FBCore/State/Messages/StateMessageProperties.h>
#include <FBCore/State/Messages/StateMessagePlay.h>
#include <FBCore/State/Messages/StateMessagePair.h>
#include <FBCore/State/Messages/StateMessageStop.h>
#include <FBCore/State/Messages/StateMessageAnimationEnable.h>
#include <FBCore/State/Messages/StateMessageObject.h>
#include <FBCore/State/Messages/StateMessageObjectsArray.h>
#include <FBCore/State/Messages/StateMessageUIntValue.h>
#include <FBCore/State/Messages/StateMessageVector2.h>
#include <FBCore/State/Messages/StateMessageVector3.h>
#include <FBCore/State/Messages/StateMessageVector4.h>
#include <FBCore/State/Messages/StateMessageSkyBox.h>
#include <FBCore/State/Messages/StateMessageType.h>
#include <FBCore/State/Messages/StateMessageAnimationEnable.h>
#include <FBCore/State/Messages/StateMessageDrawLine.h>
#include <FBCore/State/Messages/StateMessageText.h>
#include <FBCore/State/Messages/StateMessageTransform3.h>

#include <FBCore/State/States/ApplicationState.h>
#include <FBCore/State/States/InputState.h>
#include <FBCore/State/States/BoxShapeState.h>
#include <FBCore/State/States/CameraState.h>
#include <FBCore/State/States/CompositorState.h>
#include <FBCore/State/States/GraphicsMeshState.h>
#include <FBCore/State/States/GraphicsSystemState.h>
#include <FBCore/State/States/LightState.h>
#include <FBCore/State/States/MaterialPassState.h>
#include <FBCore/State/States/MaterialState.h>
#include <FBCore/State/States/MeshShapeState.h>
#include <FBCore/State/States/PhysicsSceneState.h>
#include <FBCore/State/States/RenderTextureState.h>
#include <FBCore/State/States/SceneNodeState.h>
#include <FBCore/State/States/SceneManagerState.h>
#include <FBCore/State/States/TerrainState.h>
#include <FBCore/State/States/TextureState.h>
#include <FBCore/State/States/UIElementState.h>
#include <FBCore/State/States/RenderWindowState.h>
#include <FBCore/State/States/OverlayState.h>
#include <FBCore/State/States/OverlayContainerState.h>
#include <FBCore/State/States/OverlayElementState.h>
#include <FBCore/State/States/OverlayTextState.h>
#include <FBCore/State/States/ViewportState.h>

#include <FBCore/System/ApplicationManager.h>
#include <FBCore/System/ApplicationManagerMT.h>
#include <FBCore/System/CommandManager.h>
#include <FBCore/System/CommandManagerMT.h>
#include <FBCore/System/CSelectionManager.h>
#include <FBCore/System/DebugUtil.h>
#include <FBCore/System/FactoryManager.h>
#include <FBCore/System/FrameStatistics.h>
#include <FBCore/System/Job.h>
#include <FBCore/System/JobQueue.h>
#include <FBCore/System/JobQueueTBB.h>
#include <FBCore/System/JobCoroutine.h>
#include <FBCore/System/MessageBox.h>
#include <FBCore/System/Plugin.h>
#include <FBCore/System/PluginEvent.h>
#include <FBCore/System/PluginManager.h>
#include <FBCore/System/ProcessManager.h>
#include <FBCore/System/Profile.h>
#include <FBCore/System/Profiler.h>
#include <FBCore/System/StateContext.h>
#include <FBCore/System/StateContextStandard.h>
#include <FBCore/System/StateQueue.h>
#include <FBCore/System/StateQueueStandard.h>
#include <FBCore/System/StateManagerStandard.h>
#include <FBCore/System/Task.h>
#include <FBCore/System/TaskManager.h>
#include <FBCore/System/ThreadPool.h>
#include <FBCore/System/TimerBoost.h>
#include <FBCore/System/TimerChrono.h>
#include <FBCore/System/TimerCPU.h>
#include <FBCore/System/TimerMT.h>
#include <FBCore/System/TimerWin32.h>
#include <FBCore/System/WorkerThread.h>
#include <FBCore/System/WindowMessageData.h>

#endif  // FBCoreHeaders_h__
